/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ErrorsOfflineRouteImport } from './routes/errors/offline'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as AdminAccountsRolesRouteImport } from './routes/admin/accounts/roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsOfflineRoute = ErrorsOfflineRouteImport.update({
  id: '/errors/offline',
  path: '/errors/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRolesRoute = AdminAccountsRolesRouteImport.update({
  id: '/admin/accounts/roles',
  path: '/admin/accounts/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/logs': typeof AdminLogsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/errors/404': typeof Errors404Route
  '/errors/offline': typeof ErrorsOfflineRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/logs': typeof AdminLogsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/errors/404': typeof Errors404Route
  '/errors/offline': typeof ErrorsOfflineRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/logs': typeof AdminLogsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/errors/404': typeof Errors404Route
  '/errors/offline': typeof ErrorsOfflineRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/config'
    | '/admin/logs'
    | '/auth/login'
    | '/auth/logout'
    | '/errors/404'
    | '/errors/offline'
    | '/admin'
    | '/admin/accounts/roles'
    | '/admin/accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/config'
    | '/admin/logs'
    | '/auth/login'
    | '/auth/logout'
    | '/errors/404'
    | '/errors/offline'
    | '/admin'
    | '/admin/accounts/roles'
    | '/admin/accounts'
  id:
    | '__root__'
    | '/'
    | '/admin/config'
    | '/admin/logs'
    | '/auth/login'
    | '/auth/logout'
    | '/errors/404'
    | '/errors/offline'
    | '/admin/'
    | '/admin/accounts/roles'
    | '/admin/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  Errors404Route: typeof Errors404Route
  ErrorsOfflineRoute: typeof ErrorsOfflineRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountsRolesRoute: typeof AdminAccountsRolesRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/offline': {
      id: '/errors/offline'
      path: '/errors/offline'
      fullPath: '/errors/offline'
      preLoaderRoute: typeof ErrorsOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/roles': {
      id: '/admin/accounts/roles'
      path: '/admin/accounts/roles'
      fullPath: '/admin/accounts/roles'
      preLoaderRoute: typeof AdminAccountsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminLogsRoute: AdminLogsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  Errors404Route: Errors404Route,
  ErrorsOfflineRoute: ErrorsOfflineRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountsRolesRoute: AdminAccountsRolesRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
