// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import dotenv from "dotenv";
import "dotenv/config";
import { defineConfig } from "prisma/config";

const envFile =
  process.env.NODE_ENV === "production" ? ".env.prod" : ".env.dev";

const envConfig = dotenv.config({ path: path.resolve(process.cwd(), envFile) });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envConfig.parsed?.DATABASE_URL,
  },
});
